### ISSUE TITLE
[!] Load checkpoint/u_net_all.npz failed!

### ISSUE THREAD

**Issue by afmsaif** [zsdonghao/u-net-brain-tumor#15]
while i was running this code this appears [!] Load checkpoint/u_net_all.npz failed! . what is the problem. i am running this code on cpu.

**Comment by zsdonghao** [comment]
it is correct. if only if you have a trained model, you can load it.

**Comment by afmsaif** [comment]
do i have to run train.py before model.py?

**Comment by YYsmith** [comment]
I also get this problem. Is there any solution?

**Comment by YYsmith** [comment]
We can ignore this message and the program will continue to run

**Comment by adarsheng1** [comment]
But the program gets failed after this exception.
