### ISSUE TITLE
Attribute error : tuple object has no attribute lower

### ISSUE THREAD

**Issue by achintacs90** [zsdonghao/u-net-brain-tumor#42]
while i am trying to run train.py file i get attribute error : tuple object has no attribute lower , i am using cpu for training ,
![screenshot from 2019-02-19 16-13-46](https://user-images.githubusercontent.com/43037693/53010464-03678280-3464-11e9-9929-eeac53797150.png)

**Comment by anitchris** [comment]
did you find the reason? any solution for this? faced with the same problem..

**Comment by achintacsgit** [comment]
downgrade your tensorlayer to 1.7.2
