### ISSUE TITLE
Error: Your CPU supports instructions that TensorFlow binary not compiled to use: AVX2

### ISSUE THREAD

**Issue by sapnii2** [zsdonghao/u-net-brain-tumor#49]
I am running run.py but gives error:
 

(base) G:\>cd BraTS_2018_U-Net-master

(base) G:\BraTS_2018_U-Net-master>run.py
[*] creates checkpoint ...
[*] creates samples/all ...
finished Brats18_2013_24_1
2019-06-15 22:05:45.959220: I tensorflow/core/platform/cpu_feature_guard.cc:141]
 Your CPU supports instructions that this TensorFlow binary was not compiled to
use: AVX2
Traceback (most recent call last):
  File "G:\BraTS_2018_U-Net-master\run.py", line 154, in <module>

  File "G:\BraTS_2018_U-Net-master\run.py", line 117, in main
    t_seg = tf.placeholder('float32', [1, nw, nh, 1], name='target_segment')
NameError: name 'model' is not defined

**Comment by sapnii2** [comment]
What are dependencies to run the whole code on CPU and GPU?
I installed TF 1.13. TL 2.0, PY37
Thanks, Please provide step by step process as am new to TF.
I am getting attribute errors with run.py and not able to install TL you specified.

**Comment by zsdonghao** [comment]
please downgrade TF to 0.11 and TL to 1.11

**Comment by sapnii2** [comment]
Hi,
thank you for response.
I am new user of TF. I am using Windows 8.1, CPU, Also nvidia GPU card is there but i dont know how to utilize it.
I uninstalled previous TF, TL.
Tried to install TF0.11 but the following message is on Anaconda prompt (python 3.7):
----------------------------------------------------------------------------------------
(base) G:\test>pip install tensorflow==0.11.0rc0
Collecting tensorflow==0.11.0rc0
  Could not find a version that satisfies the requirement tensorflow==0.11.0rc0
(from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 2.0.0a0, 2.0
.0b0, 2.0.0b1)
No matching distribution found for tensorflow==0.11.0rc0
----------------------------------------------------------------------------------
Can you please upload one step by step setup and execution help file for beginners?
I tried your brats2017 for past 20 days and now came across brats2018 code.
I also got brats2018 dataset from there website after registration and approval.

**Comment by sapnii2** [comment]
Hi,
thank you for the response.
I am a new user of TF. I am using Windows 8.1, CPU, Also Nvidia GPU card is there but I don't know how to utilize it.
I uninstalled previous TF, TL.
Tried to install TF0.11 but the following message is on Anaconda prompt (python 3.7):


**(base) G:\test>pip install tensorflow==0.11.0rc0
Collecting tensorflow==0.11.0rc0
Could not find a version that satisfies the requirement tensorflow==0.11.0rc0
(from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 2.0.0a0, 2.0
.0b0, 2.0.0b1)
No matching distribution found for tensorflow==0.11.0rc0**
Can you please upload one step by step setup and execution help file for beginners?
I tried your brats2017 for past 20 days and now came across the brats2018 code.
I also got brats2018 dataset from there website after registration and approval.

**Comment by sapnii2** [comment]
> I am running run.py but gives error:
> 
> (base) G:>cd BraTS_2018_U-Net-master
> 
> (base) G:\BraTS_2018_U-Net-master>run.py
> [_] creates checkpoint ... [_] creates samples/all ...
> finished Brats18_2013_24_1
> 2019-06-15 22:05:45.959220: I tensorflow/core/platform/cpu_feature_guard.cc:141]
> Your CPU supports instructions that this TensorFlow binary was not compiled to
> use: AVX2
> Traceback (most recent call last):
> File "G:\BraTS_2018_U-Net-master\run.py", line 154, in
> 
> File "G:\BraTS_2018_U-Net-master\run.py", line 117, in main
> t_seg = tf.placeholder('float32', [1, nw, nh, 1], name='target_segment')
> NameError: name 'model' is not defined

*******************I resolved my query by deleting my pychche data and reatart.

**Comment by sapnii2** [comment]
> please downgrade TF to 0.11 and TL to 1.11
