### ISSUE TITLE
TypeError: zoom_multi() got an unexpected keyword argument 'is_random'

### ISSUE THREAD

**Issue by shenzeqi** [zsdonghao/u-net-brain-tumor#55]
Lossy conversion from float64 to uint8. Range [-0.18539370596408844, 2.158207416534424]. Convert image to uint8 prior to saving to suppress this warning.
Traceback (most recent call last):
  File "train.py", line 250, in <module>
    main(args.task)
  File "train.py", line 106, in main
    X[:,:,2,np.newaxis], X[:,:,3,np.newaxis], y])#[:,:,np.newaxis]])
  File "train.py", line 26, in distort_imgs
    fill_mode='constant')
TypeError: zoom_multi() got an unexpected keyword argument 'is_random'

**Comment by BTapan** [comment]
Can you share thr answer of this issue please, I got the same issue.

**Comment by Anuj-IITBHU** [comment]
I am also getting the same issue, Could you help, please!

**Comment by BTapan** [comment]
@Anuj-IITBHU If you are using new tensorlayer and tesnsorflow versions, then don't use them
use tensorlayer==1.6.0 and tensorflow==1.13.1

**Comment by Anuj-IITBHU** [comment]
Thank You for the help. To eliminate further errors I had to run it in python 3.5, with scipy version 0.18.0 and tensorflow and tensorlayer as stated above.

**Comment by biswajit310** [comment]
I face the same error while running the same code from github. Will follow the idesa shared by @Anuj-IITBHU and @BTapan . I am currently running on my CPU machine with 4 gb ram. how many hgg and lgg will I consider for smooth running of the code. plz. guide me. Or can anyone say the setup to run it on google colab.

**Comment by Anuj-IITBHU** [comment]
While running for the full dataset on CPU, each epoch took about 6-7 hours while on GPU with 10gb memory, each epoch took 40-45 minutes.

**Comment by biswajit310** [comment]
@Anuj-IITBHU Thank you!!

**Comment by biswajit310** [comment]
Also run on python 3.8 also.
